/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UpdateTrigger Options for updating a build trigger
type UpdateTrigger struct {
	// Whether the build trigger is enabled
	Enabled bool `json:"enabled"`
}

// NewUpdateTrigger instantiates a new UpdateTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTrigger(enabled bool) *UpdateTrigger {
	this := UpdateTrigger{}
	this.Enabled = enabled
	return &this
}

// NewUpdateTriggerWithDefaults instantiates a new UpdateTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTriggerWithDefaults() *UpdateTrigger {
	this := UpdateTrigger{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *UpdateTrigger) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateTrigger) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateTrigger) SetEnabled(v bool) {
	o.Enabled = v
}

func (o UpdateTrigger) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateTrigger struct {
	value *UpdateTrigger
	isSet bool
}

func (v NullableUpdateTrigger) Get() *UpdateTrigger {
	return v.value
}

func (v *NullableUpdateTrigger) Set(val *UpdateTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTrigger(val *UpdateTrigger) *NullableUpdateTrigger {
	return &NullableUpdateTrigger{value: val, isSet: true}
}

func (v NullableUpdateTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
