/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// TokenPermission Description of a token permission
type TokenPermission struct {
	// Role to use for the token
	Role string `json:"role"`
}

// NewTokenPermission instantiates a new TokenPermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenPermission(role string) *TokenPermission {
	this := TokenPermission{}
	this.Role = role
	return &this
}

// NewTokenPermissionWithDefaults instantiates a new TokenPermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenPermissionWithDefaults() *TokenPermission {
	this := TokenPermission{}
	return &this
}

// GetRole returns the Role field value
func (o *TokenPermission) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *TokenPermission) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *TokenPermission) SetRole(v string) {
	o.Role = v
}

func (o TokenPermission) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["role"] = o.Role
	}
	return json.Marshal(toSerialize)
}

type NullableTokenPermission struct {
	value *TokenPermission
	isSet bool
}

func (v NullableTokenPermission) Get() *TokenPermission {
	return v.value
}

func (v *NullableTokenPermission) Set(val *TokenPermission) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenPermission) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenPermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenPermission(val *TokenPermission) *NullableTokenPermission {
	return &NullableTokenPermission{value: val, isSet: true}
}

func (v NullableTokenPermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenPermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
