/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// BuildTriggerActivateRequest struct for BuildTriggerActivateRequest
type BuildTriggerActivateRequest struct {
	// The name of the robot that will be used to pull images.
	PullRobot *string `json:"pull_robot,omitempty"`
	// Arbitrary json.
	Config map[string]interface{} `json:"config"`
}

// NewBuildTriggerActivateRequest instantiates a new BuildTriggerActivateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildTriggerActivateRequest(config map[string]interface{}) *BuildTriggerActivateRequest {
	this := BuildTriggerActivateRequest{}
	this.Config = config
	return &this
}

// NewBuildTriggerActivateRequestWithDefaults instantiates a new BuildTriggerActivateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildTriggerActivateRequestWithDefaults() *BuildTriggerActivateRequest {
	this := BuildTriggerActivateRequest{}
	return &this
}

// GetPullRobot returns the PullRobot field value if set, zero value otherwise.
func (o *BuildTriggerActivateRequest) GetPullRobot() string {
	if o == nil || o.PullRobot == nil {
		var ret string
		return ret
	}
	return *o.PullRobot
}

// GetPullRobotOk returns a tuple with the PullRobot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildTriggerActivateRequest) GetPullRobotOk() (*string, bool) {
	if o == nil || o.PullRobot == nil {
		return nil, false
	}
	return o.PullRobot, true
}

// HasPullRobot returns a boolean if a field has been set.
func (o *BuildTriggerActivateRequest) HasPullRobot() bool {
	if o != nil && o.PullRobot != nil {
		return true
	}

	return false
}

// SetPullRobot gets a reference to the given string and assigns it to the PullRobot field.
func (o *BuildTriggerActivateRequest) SetPullRobot(v string) {
	o.PullRobot = &v
}

// GetConfig returns the Config field value
func (o *BuildTriggerActivateRequest) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *BuildTriggerActivateRequest) GetConfigOk() (*map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *BuildTriggerActivateRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o BuildTriggerActivateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PullRobot != nil {
		toSerialize["pull_robot"] = o.PullRobot
	}
	if true {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableBuildTriggerActivateRequest struct {
	value *BuildTriggerActivateRequest
	isSet bool
}

func (v NullableBuildTriggerActivateRequest) Get() *BuildTriggerActivateRequest {
	return v.value
}

func (v *NullableBuildTriggerActivateRequest) Set(val *BuildTriggerActivateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildTriggerActivateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildTriggerActivateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildTriggerActivateRequest(val *BuildTriggerActivateRequest) *NullableBuildTriggerActivateRequest {
	return &NullableBuildTriggerActivateRequest{value: val, isSet: true}
}

func (v NullableBuildTriggerActivateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildTriggerActivateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
