/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PrototypeUpdate Description of a the new prototype role
type PrototypeUpdate struct {
	// Role that should be applied to the permission
	Role string `json:"role"`
}

// NewPrototypeUpdate instantiates a new PrototypeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrototypeUpdate(role string) *PrototypeUpdate {
	this := PrototypeUpdate{}
	this.Role = role
	return &this
}

// NewPrototypeUpdateWithDefaults instantiates a new PrototypeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrototypeUpdateWithDefaults() *PrototypeUpdate {
	this := PrototypeUpdate{}
	return &this
}

// GetRole returns the Role field value
func (o *PrototypeUpdate) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *PrototypeUpdate) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *PrototypeUpdate) SetRole(v string) {
	o.Role = v
}

func (o PrototypeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["role"] = o.Role
	}
	return json.Marshal(toSerialize)
}

type NullablePrototypeUpdate struct {
	value *PrototypeUpdate
	isSet bool
}

func (v NullablePrototypeUpdate) Get() *PrototypeUpdate {
	return v.value
}

func (v *NullablePrototypeUpdate) Set(val *PrototypeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullablePrototypeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullablePrototypeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrototypeUpdate(val *PrototypeUpdate) *NullablePrototypeUpdate {
	return &NullablePrototypeUpdate{value: val, isSet: true}
}

func (v NullablePrototypeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrototypeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
