/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// NewRepo Description of a new repository
type NewRepo struct {
	// Namespace in which the repository should be created. If omitted, the username of the caller is used
	Namespace *string `json:"namespace,omitempty"`
	// Visibility which the repository will start with
	Visibility string `json:"visibility"`
	// Repository name
	Repository string `json:"repository"`
	// Markdown encoded description for the repository
	Description string `json:"description"`
}

// NewNewRepo instantiates a new NewRepo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewRepo(visibility string, repository string, description string) *NewRepo {
	this := NewRepo{}
	this.Visibility = visibility
	this.Repository = repository
	this.Description = description
	return &this
}

// NewNewRepoWithDefaults instantiates a new NewRepo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewRepoWithDefaults() *NewRepo {
	this := NewRepo{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *NewRepo) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewRepo) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *NewRepo) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *NewRepo) SetNamespace(v string) {
	o.Namespace = &v
}

// GetVisibility returns the Visibility field value
func (o *NewRepo) GetVisibility() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value
// and a boolean to check if the value has been set.
func (o *NewRepo) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visibility, true
}

// SetVisibility sets field value
func (o *NewRepo) SetVisibility(v string) {
	o.Visibility = v
}

// GetRepository returns the Repository field value
func (o *NewRepo) GetRepository() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value
// and a boolean to check if the value has been set.
func (o *NewRepo) GetRepositoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repository, true
}

// SetRepository sets field value
func (o *NewRepo) SetRepository(v string) {
	o.Repository = v
}

// GetDescription returns the Description field value
func (o *NewRepo) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *NewRepo) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *NewRepo) SetDescription(v string) {
	o.Description = v
}

func (o NewRepo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if true {
		toSerialize["visibility"] = o.Visibility
	}
	if true {
		toSerialize["repository"] = o.Repository
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableNewRepo struct {
	value *NewRepo
	isSet bool
}

func (v NullableNewRepo) Get() *NewRepo {
	return v.value
}

func (v *NullableNewRepo) Set(val *NewRepo) {
	v.value = val
	v.isSet = true
}

func (v NullableNewRepo) IsSet() bool {
	return v.isSet
}

func (v *NullableNewRepo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewRepo(val *NewRepo) *NullableNewRepo {
	return &NullableNewRepo{value: val, isSet: true}
}

func (v NullableNewRepo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewRepo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
