/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UpdateApp Description of an updated application.
type UpdateApp struct {
	// The URI for the application's OAuth redirect
	RedirectUri string `json:"redirect_uri"`
	// The e-mail address of the avatar to use for the application
	AvatarEmail *string `json:"avatar_email,omitempty"`
	// The name of the application
	Name string `json:"name"`
	// The URI for the application's homepage
	ApplicationUri string `json:"application_uri"`
	// The human-readable description for the application
	Description *string `json:"description,omitempty"`
}

// NewUpdateApp instantiates a new UpdateApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateApp(redirectUri string, name string, applicationUri string) *UpdateApp {
	this := UpdateApp{}
	this.RedirectUri = redirectUri
	this.Name = name
	this.ApplicationUri = applicationUri
	return &this
}

// NewUpdateAppWithDefaults instantiates a new UpdateApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAppWithDefaults() *UpdateApp {
	this := UpdateApp{}
	return &this
}

// GetRedirectUri returns the RedirectUri field value
func (o *UpdateApp) GetRedirectUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value
// and a boolean to check if the value has been set.
func (o *UpdateApp) GetRedirectUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUri, true
}

// SetRedirectUri sets field value
func (o *UpdateApp) SetRedirectUri(v string) {
	o.RedirectUri = v
}

// GetAvatarEmail returns the AvatarEmail field value if set, zero value otherwise.
func (o *UpdateApp) GetAvatarEmail() string {
	if o == nil || o.AvatarEmail == nil {
		var ret string
		return ret
	}
	return *o.AvatarEmail
}

// GetAvatarEmailOk returns a tuple with the AvatarEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateApp) GetAvatarEmailOk() (*string, bool) {
	if o == nil || o.AvatarEmail == nil {
		return nil, false
	}
	return o.AvatarEmail, true
}

// HasAvatarEmail returns a boolean if a field has been set.
func (o *UpdateApp) HasAvatarEmail() bool {
	if o != nil && o.AvatarEmail != nil {
		return true
	}

	return false
}

// SetAvatarEmail gets a reference to the given string and assigns it to the AvatarEmail field.
func (o *UpdateApp) SetAvatarEmail(v string) {
	o.AvatarEmail = &v
}

// GetName returns the Name field value
func (o *UpdateApp) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateApp) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateApp) SetName(v string) {
	o.Name = v
}

// GetApplicationUri returns the ApplicationUri field value
func (o *UpdateApp) GetApplicationUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationUri
}

// GetApplicationUriOk returns a tuple with the ApplicationUri field value
// and a boolean to check if the value has been set.
func (o *UpdateApp) GetApplicationUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationUri, true
}

// SetApplicationUri sets field value
func (o *UpdateApp) SetApplicationUri(v string) {
	o.ApplicationUri = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateApp) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateApp) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateApp) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateApp) SetDescription(v string) {
	o.Description = &v
}

func (o UpdateApp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["redirect_uri"] = o.RedirectUri
	}
	if o.AvatarEmail != nil {
		toSerialize["avatar_email"] = o.AvatarEmail
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["application_uri"] = o.ApplicationUri
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateApp struct {
	value *UpdateApp
	isSet bool
}

func (v NullableUpdateApp) Get() *UpdateApp {
	return v.value
}

func (v *NullableUpdateApp) Set(val *UpdateApp) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateApp) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateApp(val *UpdateApp) *NullableUpdateApp {
	return &NullableUpdateApp{value: val, isSet: true}
}

func (v NullableUpdateApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
