/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UpdateOrg Description of updates for an existing organization
type UpdateOrg struct {
	// Whether the organization desires to receive emails for invoices
	InvoiceEmail *bool `json:"invoice_email,omitempty"`
	// Organization contact email
	Email *string `json:"email,omitempty"`
	// The number of seconds for tag expiration
	TagExpirationS *int32 `json:"tag_expiration_s,omitempty"`
}

// NewUpdateOrg instantiates a new UpdateOrg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrg() *UpdateOrg {
	this := UpdateOrg{}
	return &this
}

// NewUpdateOrgWithDefaults instantiates a new UpdateOrg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrgWithDefaults() *UpdateOrg {
	this := UpdateOrg{}
	return &this
}

// GetInvoiceEmail returns the InvoiceEmail field value if set, zero value otherwise.
func (o *UpdateOrg) GetInvoiceEmail() bool {
	if o == nil || o.InvoiceEmail == nil {
		var ret bool
		return ret
	}
	return *o.InvoiceEmail
}

// GetInvoiceEmailOk returns a tuple with the InvoiceEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrg) GetInvoiceEmailOk() (*bool, bool) {
	if o == nil || o.InvoiceEmail == nil {
		return nil, false
	}
	return o.InvoiceEmail, true
}

// HasInvoiceEmail returns a boolean if a field has been set.
func (o *UpdateOrg) HasInvoiceEmail() bool {
	if o != nil && o.InvoiceEmail != nil {
		return true
	}

	return false
}

// SetInvoiceEmail gets a reference to the given bool and assigns it to the InvoiceEmail field.
func (o *UpdateOrg) SetInvoiceEmail(v bool) {
	o.InvoiceEmail = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UpdateOrg) GetEmail() string {
	if o == nil || o.Email == nil {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrg) GetEmailOk() (*string, bool) {
	if o == nil || o.Email == nil {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UpdateOrg) HasEmail() bool {
	if o != nil && o.Email != nil {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UpdateOrg) SetEmail(v string) {
	o.Email = &v
}

// GetTagExpirationS returns the TagExpirationS field value if set, zero value otherwise.
func (o *UpdateOrg) GetTagExpirationS() int32 {
	if o == nil || o.TagExpirationS == nil {
		var ret int32
		return ret
	}
	return *o.TagExpirationS
}

// GetTagExpirationSOk returns a tuple with the TagExpirationS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrg) GetTagExpirationSOk() (*int32, bool) {
	if o == nil || o.TagExpirationS == nil {
		return nil, false
	}
	return o.TagExpirationS, true
}

// HasTagExpirationS returns a boolean if a field has been set.
func (o *UpdateOrg) HasTagExpirationS() bool {
	if o != nil && o.TagExpirationS != nil {
		return true
	}

	return false
}

// SetTagExpirationS gets a reference to the given int32 and assigns it to the TagExpirationS field.
func (o *UpdateOrg) SetTagExpirationS(v int32) {
	o.TagExpirationS = &v
}

func (o UpdateOrg) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.InvoiceEmail != nil {
		toSerialize["invoice_email"] = o.InvoiceEmail
	}
	if o.Email != nil {
		toSerialize["email"] = o.Email
	}
	if o.TagExpirationS != nil {
		toSerialize["tag_expiration_s"] = o.TagExpirationS
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateOrg struct {
	value *UpdateOrg
	isSet bool
}

func (v NullableUpdateOrg) Get() *UpdateOrg {
	return v.value
}

func (v *NullableUpdateOrg) Set(val *UpdateOrg) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrg) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrg(val *UpdateOrg) *NullableUpdateOrg {
	return &NullableUpdateOrg{value: val, isSet: true}
}

func (v NullableUpdateOrg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
