/*
 * Quay Frontend
 *
 * This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.
 *
 * API version: v1
 * Contact: support@quay.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// CreateMessage Create a new message
type CreateMessage struct {
	Message *CreateMessageMessage `json:"message,omitempty"`
}

// NewCreateMessage instantiates a new CreateMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMessage() *CreateMessage {
	this := CreateMessage{}
	return &this
}

// NewCreateMessageWithDefaults instantiates a new CreateMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMessageWithDefaults() *CreateMessage {
	this := CreateMessage{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateMessage) GetMessage() CreateMessageMessage {
	if o == nil || o.Message == nil {
		var ret CreateMessageMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMessage) GetMessageOk() (*CreateMessageMessage, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateMessage) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given CreateMessageMessage and assigns it to the Message field.
func (o *CreateMessage) SetMessage(v CreateMessageMessage) {
	o.Message = &v
}

func (o CreateMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableCreateMessage struct {
	value *CreateMessage
	isSet bool
}

func (v NullableCreateMessage) Get() *CreateMessage {
	return v.value
}

func (v *NullableCreateMessage) Set(val *CreateMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMessage(val *CreateMessage) *NullableCreateMessage {
	return &NullableCreateMessage{value: val, isSet: true}
}

func (v NullableCreateMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
